// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportFourthProject.Api.Data;

#nullable disable

namespace TransportFourthProject.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905193611_updateSizeOfPasswordAndNationalNumber")]
    partial class updateSizeOfPasswordAndNationalNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportFourthProject.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDiscountTicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserDiscountTicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BusTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusNumber")
                        .IsUnique();

                    b.HasIndex("BusTypeId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.BusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            IsDeleted = false,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            IsDeleted = false,
                            Type = "VIP"
                        });
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allepo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Damascus"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Homs"
                        });
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NationalNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.PaymentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.RoutePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<int>("EndCityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StartCityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusTypeId");

                    b.HasIndex("EndCityId");

                    b.HasIndex("StartCityId");

                    b.ToTable("RoutePrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusTypeId = 1,
                            DistanceKm = 0m,
                            DurationHours = 5,
                            EndCityId = 2,
                            IsDeleted = false,
                            Price = 1200m,
                            StartCityId = 1
                        },
                        new
                        {
                            Id = 2,
                            BusTypeId = 1,
                            DistanceKm = 0m,
                            DurationHours = 5,
                            EndCityId = 1,
                            IsDeleted = false,
                            Price = 1200m,
                            StartCityId = 2
                        },
                        new
                        {
                            Id = 3,
                            BusTypeId = 1,
                            DistanceKm = 0m,
                            DurationHours = 3,
                            EndCityId = 1,
                            IsDeleted = false,
                            Price = 800m,
                            StartCityId = 3
                        },
                        new
                        {
                            Id = 4,
                            BusTypeId = 1,
                            DistanceKm = 0m,
                            DurationHours = 3,
                            EndCityId = 3,
                            IsDeleted = false,
                            Price = 800m,
                            StartCityId = 1
                        },
                        new
                        {
                            Id = 5,
                            BusTypeId = 2,
                            DistanceKm = 0m,
                            DurationHours = 5,
                            EndCityId = 2,
                            IsDeleted = false,
                            Price = 1500m,
                            StartCityId = 1
                        },
                        new
                        {
                            Id = 6,
                            BusTypeId = 2,
                            DistanceKm = 0m,
                            DurationHours = 5,
                            EndCityId = 1,
                            IsDeleted = false,
                            Price = 1500m,
                            StartCityId = 2
                        },
                        new
                        {
                            Id = 7,
                            BusTypeId = 2,
                            DistanceKm = 0m,
                            DurationHours = 3,
                            EndCityId = 1,
                            IsDeleted = false,
                            Price = 1000m,
                            StartCityId = 3
                        },
                        new
                        {
                            Id = 8,
                            BusTypeId = 2,
                            DistanceKm = 0m,
                            DurationHours = 3,
                            EndCityId = 3,
                            IsDeleted = false,
                            Price = 1000m,
                            StartCityId = 1
                        });
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsArrived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoutePriceId")
                        .HasColumnType("int");

                    b.Property<int?>("TripDiscountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoutePriceId");

                    b.HasIndex("TripDiscountId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.TripDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TripDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adha-Aid discount",
                            Percentage = 10,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Christmas discount",
                            Percentage = 20,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Labor day discount",
                            Percentage = 30,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NationalNumber")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.UserDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Student discount",
                            Percentage = 20,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Engineer discount",
                            Percentage = 40,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patient discount",
                            Percentage = 50,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.UserDiscountTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDiscountTickets");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Booking", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.UserDiscountTicket", "UserDiscountTicket")
                        .WithMany("Bookings")
                        .HasForeignKey("UserDiscountTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransportFourthProject.Api.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");

                    b.Navigation("UserDiscountTicket");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Bus", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.BusType", "BusType")
                        .WithMany("Buses")
                        .HasForeignKey("BusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Payment", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("TransportFourthProject.Api.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.PaymentAttempt", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.Payment", "Payment")
                        .WithMany("Attempts")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("TransportFourthProject.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.RoutePrice", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.BusType", "BusType")
                        .WithMany("RoutePrices")
                        .HasForeignKey("BusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.City", "EndCity")
                        .WithMany("EndCityRoutePrices")
                        .HasForeignKey("EndCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.City", "StartCity")
                        .WithMany("StartCityRoutePrices")
                        .HasForeignKey("StartCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusType");

                    b.Navigation("EndCity");

                    b.Navigation("StartCity");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Trip", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.Employee", "Employee")
                        .WithMany("Trips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.RoutePrice", "RoutePrice")
                        .WithMany("Trips")
                        .HasForeignKey("RoutePriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.TripDiscount", "TripDiscount")
                        .WithMany("Trips")
                        .HasForeignKey("TripDiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bus");

                    b.Navigation("Employee");

                    b.Navigation("RoutePrice");

                    b.Navigation("TripDiscount");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.UserDiscountTicket", b =>
                {
                    b.HasOne("TransportFourthProject.Api.Models.UserDiscount", "UserDiscount")
                        .WithMany("UserDiscountTickets")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportFourthProject.Api.Models.User", "User")
                        .WithMany("UserDiscountTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserDiscount");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Booking", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Bus", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.BusType", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("RoutePrices");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.City", b =>
                {
                    b.Navigation("EndCityRoutePrices");

                    b.Navigation("StartCityRoutePrices");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Employee", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Payment", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.RoutePrice", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.Trip", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.TripDiscount", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserDiscountTickets");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.UserDiscount", b =>
                {
                    b.Navigation("UserDiscountTickets");
                });

            modelBuilder.Entity("TransportFourthProject.Api.Models.UserDiscountTicket", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
